[phases.setup]
nixPkgs = ["python39"]

[phases.install]
commands = [
    "pip install -r requirements.txt"
]

[phases.build]
commands = []

[phases.start]
command = "python app.py"

[phases.start]
command = "gunicorn app:app --bind 0.0.0.0:$PORT"
